SELECT *
FROM CITY
WHERE POPULATION > 100000
AND COUNTRYCODE = 'USA';

SELECT NAME
FROM CITY
WHERE POPULATION > 120000
AND COUNTRYCODE = 'USA';

SELECT *
FROM CITY

SELECT *
FROM CITY
WHERE ID = 1661;

SELECT *
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT CITY, STATE
FROM STATION;

SELECT DISTINCT(CITY)
FROM STATION
WHERE ((ID % 2) = 0)
ORDER BY CITY ASC;

SELECT( (COUNT(CITY)) - COUNT(DISTINCT(CITY)))
FROM STATION;

  (
SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY ASC
     LIMIT 1
 )
 UNION ALL
 (
SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY LENGTH(CITY) ASC, CITY ASC
     LIMIT 1
 );

 SELECT DISTINCT(CITY)
FROM STATION
WHERE left(CITY,1) IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE right(CITY,1) IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE right(CITY,1) IN ('a','i', 'u', 'e','o')
AND left(CITY,1) IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE left(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE RIGHT(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE RIGHT(CITY,1) NOT IN ('a','i', 'u', 'e','o')
OR LEFT(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE RIGHT(CITY,1) NOT IN ('a','i', 'u', 'e','o')
AND LEFT(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT NAME
FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME,3) ASC, ID ASC;

SELECT name
FROM Employee
ORDER BY name ASC;

SELECT name 
FROM Employee
WHERE salary > 2000
AND months < 10
ORDER BY employee_id ASC;

SELECT 
    CASE
        WHEN A + B <= C OR B + C <= A OR C + A <= B THEN "Not A Triangle"
        WHEN A = B AND B = C THEN 'Equilateral'
        WHEN (A = B) OR (B = C) OR (A = C) THEN 'Isosceles'
        WHEN A <> B AND B <> C AND A <> C THEN 'Scalene'
    END
FROM TRIANGLES;

SELECT CONCAT(Name,'(',LEFT(Occupation,1),')')
FROM OCCUPATIONS
ORDER BY name;

SELECT CONCAT('There are a total of ',COUNT(occupation),' ',LOWER(occupation),'s.')
FROM OCCUPATIONS
GROUP BY occupation
ORDER BY COUNT(occupation),occupation;

SELECT COUNT(ID)
FROM CITY
WHERE POPULATION > 100000;

SELECT SUM(POPULATION)
FROM CITY
WHERE District = 'California';

SELECT AVG(POPULATION)
FROM CITY
WHERE District = 'California';

SELECT ROUND(AVG(POPULATION))
FROM CITY;

SELECT SUM(POPULATION)
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT (MAX(POPULATION)-MIN(POPULATION))
FROM CITY;

SELECT CEIL((SELECT AVG(Salary)
FROM EMPLOYEES
WHERE Salary <> 0) - AVG(CAST(REPLACE(Salary, '0', '') AS UNSIGNED)))
FROM EMPLOYEES;

SELECT MAX(total_earnings) AS max_earnings, 
       COUNT(*) AS employee_count
FROM (
    SELECT employee_id, (months * salary) AS total_earnings
    FROM Employee
) AS earnings
WHERE total_earnings = (
    SELECT MAX(months * salary)
    FROM Employee
);

SELECT ROUND(SUM(LAT_N),2), ROUND(SUM(LONG_W),2)
FROM STATION;

SELECT ROUND(SUM(LAT_N), 4)
FROM STATION
WHERE LAT_N > 38.7880
AND LAT_N < 137.2345;

SELECT MAX(ROUND(LAT_N,4))
FROM STATION
WHERE LAT_N < 137.2345;

SELECT ROUND(LONG_W,4)
FROM STATION 
WHERE LAT_N = (SELECT MAX(LAT_N)
              FROM STATION
              WHERE LAT_N < 137.2345);
              