SELECT *
FROM CITY
WHERE POPULATION > 100000
AND COUNTRYCODE = 'USA';

SELECT NAME
FROM CITY
WHERE POPULATION > 120000
AND COUNTRYCODE = 'USA';

SELECT *
FROM CITY

SELECT *
FROM CITY
WHERE ID = 1661;

SELECT *
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'JPN';

SELECT CITY, STATE
FROM STATION;

SELECT DISTINCT(CITY)
FROM STATION
WHERE ((ID % 2) = 0)
ORDER BY CITY ASC;

SELECT( (COUNT(CITY)) - COUNT(DISTINCT(CITY)))
FROM STATION;

  (
SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY LENGTH(CITY) DESC, CITY ASC
     LIMIT 1
 )
 UNION ALL
 (
SELECT CITY, LENGTH(CITY)
    FROM STATION
    ORDER BY LENGTH(CITY) ASC, CITY ASC
     LIMIT 1
 );

 SELECT DISTINCT(CITY)
FROM STATION
WHERE left(CITY,1) IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE right(CITY,1) IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE right(CITY,1) IN ('a','i', 'u', 'e','o')
AND left(CITY,1) IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE left(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE RIGHT(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE RIGHT(CITY,1) NOT IN ('a','i', 'u', 'e','o')
OR LEFT(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT DISTINCT(CITY)
FROM STATION
WHERE RIGHT(CITY,1) NOT IN ('a','i', 'u', 'e','o')
AND LEFT(CITY,1) NOT IN ('a','i', 'u', 'e','o');

SELECT NAME
FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME,3) ASC, ID ASC;

SELECT name
FROM Employee
ORDER BY name ASC;

SELECT name 
FROM Employee
WHERE salary > 2000
AND months < 10
ORDER BY employee_id ASC;

SELECT 
    CASE
        WHEN A + B <= C OR B + C <= A OR C + A <= B THEN "Not A Triangle"
        WHEN A = B AND B = C THEN 'Equilateral'
        WHEN (A = B) OR (B = C) OR (A = C) THEN 'Isosceles'
        WHEN A <> B AND B <> C AND A <> C THEN 'Scalene'
    END
FROM TRIANGLES;
